server:
  port: 8085
  
  
  
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    password: rzhasqlqikxleskd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: fau.obregon@gmail.com
    
# ESPECIFICACION DEL KAFKA SERVER  
  kafka:
    bootstrap-servers: broker:9093
    consumer:
      group-id: myGroup
